name: bblturb-analysis
channels:
  - conda-forge
dependencies:
  # Temporarily pinning dask version
  - dask!=2021.3.0
  - xarray
  - xrft
  - jupyterlab
  - netCDF4
  - h5py
  - pytables
  - gsw
  - matplotlib
  - xgcm
  - xmitgcm
  - pip
  - pip:
    - git+https://github.com/xgcm/xhistogram
